[INFO] 08 七月 09:46:53.025 上午 WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Using default implementation for ThreadExecutor

[INFO] 08 七月 09:46:53.029 上午 WrapperSimpleAppMain [org.quartz.simpl.SimpleThreadPool]
Job execution threads will use class loader of thread: WrapperSimpleAppMain

[INFO] 08 七月 09:46:53.049 上午 WrapperSimpleAppMain [org.quartz.core.SchedulerSignalerImpl]
Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl

[INFO] 08 七月 09:46:53.051 上午 WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Quartz Scheduler v.2.1.7 created.

[INFO] 08 七月 09:46:53.052 上午 WrapperSimpleAppMain [org.quartz.simpl.RAMJobStore]
RAMJobStore initialized.

[INFO] 08 七月 09:46:53.053 上午 WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Scheduler meta-data: Quartz Scheduler (v2.1.7) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.


[INFO] 08 七月 09:46:53.054 上午 WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'

[INFO] 08 七月 09:46:53.054 上午 WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Quartz scheduler version: 2.1.7

[INFO] 08 七月 09:46:53.086 上午 WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.

[ERROR] 08 七月 09:52:45.502 上午 Thread-2 [org.apache.thrift.ProcessFunction]
Internal error processing addPlanTarget

com.mongodb.MongoException$Network: can't call something : localhost/127.0.0.1:27017/ifdatadb
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:664)
	at org.cz.epm.data.manager.MongoManager.FineOne(MongoManager.java:76)
	at org.cz.epm.thrift.service.DatahouseBase.getData(DatahouseBase.java:290)
	at org.cz.epm.resource.Mapper.getMapKeyValue(Mapper.java:52)
	at org.cz.epm.resource.Mapper.GetMapKey(Mapper.java:19)
	at org.cz.epm.thrift.service.EpmDatahouseImpl.addPlanTarget(EpmDatahouseImpl.java:87)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1388)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:478)
	at org.apache.thrift.server.TNonblockingServer.requestInvoke(TNonblockingServer.java:115)
	at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:209)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:198)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:154)
Caused by: java.io.IOException: couldn't connect to [localhost/127.0.0.1:27017] bc:java.net.ConnectException: 拒绝连接
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 19 more
[INFO] 08 Jul 10:16:32.482 AM WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Using default implementation for ThreadExecutor

[INFO] 08 Jul 10:16:32.514 AM WrapperSimpleAppMain [org.quartz.simpl.SimpleThreadPool]
Job execution threads will use class loader of thread: WrapperSimpleAppMain

[INFO] 08 Jul 10:16:32.533 AM WrapperSimpleAppMain [org.quartz.core.SchedulerSignalerImpl]
Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl

[INFO] 08 Jul 10:16:32.535 AM WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Quartz Scheduler v.2.1.7 created.

[INFO] 08 Jul 10:16:32.536 AM WrapperSimpleAppMain [org.quartz.simpl.RAMJobStore]
RAMJobStore initialized.

[INFO] 08 Jul 10:16:32.537 AM WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Scheduler meta-data: Quartz Scheduler (v2.1.7) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.


[INFO] 08 Jul 10:16:32.538 AM WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'

[INFO] 08 Jul 10:16:32.538 AM WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Quartz scheduler version: 2.1.7

[INFO] 08 Jul 10:16:32.605 AM WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.

[ERROR] 08 Jul 01:06:39.647 PM Thread-2 [org.apache.thrift.ProcessFunction]
Internal error processing addPlanTarget

com.mongodb.MongoException$Network: can't call something : localhost/127.0.0.1:27017/ifdatadb
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:664)
	at org.cz.epm.data.manager.MongoManager.FineOne(MongoManager.java:76)
	at org.cz.epm.thrift.service.DatahouseBase.getData(DatahouseBase.java:290)
	at org.cz.epm.resource.Mapper.getMapKeyValue(Mapper.java:52)
	at org.cz.epm.resource.Mapper.GetMapKey(Mapper.java:19)
	at org.cz.epm.thrift.service.EpmDatahouseImpl.addPlanTarget(EpmDatahouseImpl.java:87)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1388)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:478)
	at org.apache.thrift.server.TNonblockingServer.requestInvoke(TNonblockingServer.java:115)
	at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:209)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:198)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:154)
Caused by: java.io.IOException: couldn't connect to [localhost/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 19 more
[ERROR] 08 Jul 01:07:35.021 PM Thread-2 [org.apache.thrift.ProcessFunction]
Internal error processing addPlanTarget

com.mongodb.MongoException$Network: can't call something : localhost/127.0.0.1:27017/ifdatadb
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:664)
	at org.cz.epm.data.manager.MongoManager.FineOne(MongoManager.java:76)
	at org.cz.epm.thrift.service.DatahouseBase.getData(DatahouseBase.java:290)
	at org.cz.epm.resource.Mapper.getMapKeyValue(Mapper.java:52)
	at org.cz.epm.resource.Mapper.GetMapKey(Mapper.java:19)
	at org.cz.epm.thrift.service.EpmDatahouseImpl.addPlanTarget(EpmDatahouseImpl.java:87)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1388)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:478)
	at org.apache.thrift.server.TNonblockingServer.requestInvoke(TNonblockingServer.java:115)
	at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:209)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:198)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:154)
Caused by: java.io.IOException: couldn't connect to [localhost/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 19 more
[ERROR] 08 Jul 01:16:19.226 PM Thread-2 [org.apache.thrift.ProcessFunction]
Internal error processing addPlanTarget

com.mongodb.MongoException$Network: can't call something : localhost/127.0.0.1:27017/ifdatadb
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:664)
	at org.cz.epm.data.manager.MongoManager.FineOne(MongoManager.java:76)
	at org.cz.epm.thrift.service.DatahouseBase.getData(DatahouseBase.java:290)
	at org.cz.epm.resource.Mapper.getMapKeyValue(Mapper.java:52)
	at org.cz.epm.resource.Mapper.GetMapKey(Mapper.java:19)
	at org.cz.epm.thrift.service.EpmDatahouseImpl.addPlanTarget(EpmDatahouseImpl.java:87)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1388)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:478)
	at org.apache.thrift.server.TNonblockingServer.requestInvoke(TNonblockingServer.java:115)
	at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:209)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:198)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:154)
Caused by: java.io.IOException: couldn't connect to [localhost/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 19 more
[ERROR] 08 Jul 01:19:56.797 PM Thread-2 [org.apache.thrift.ProcessFunction]
Internal error processing addPlanTarget

com.mongodb.MongoException$Network: can't call something : localhost/127.0.0.1:27017/ifdatadb
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:664)
	at org.cz.epm.data.manager.MongoManager.FineOne(MongoManager.java:76)
	at org.cz.epm.thrift.service.DatahouseBase.getData(DatahouseBase.java:290)
	at org.cz.epm.resource.Mapper.getMapKeyValue(Mapper.java:52)
	at org.cz.epm.resource.Mapper.GetMapKey(Mapper.java:19)
	at org.cz.epm.thrift.service.EpmDatahouseImpl.addPlanTarget(EpmDatahouseImpl.java:87)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1388)
	at org.cz.epm.thrift.generated.Datahouse$Processor$addPlanTarget.getResult(Datahouse.java:1)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:478)
	at org.apache.thrift.server.TNonblockingServer.requestInvoke(TNonblockingServer.java:115)
	at org.apache.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:209)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:198)
	at org.apache.thrift.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:154)
Caused by: java.io.IOException: couldn't connect to [localhost/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 19 more
[INFO] 08 七月 01:22:02.847 下午 WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Using default implementation for ThreadExecutor

[INFO] 08 七月 01:22:02.851 下午 WrapperSimpleAppMain [org.quartz.simpl.SimpleThreadPool]
Job execution threads will use class loader of thread: WrapperSimpleAppMain

[INFO] 08 七月 01:22:02.871 下午 WrapperSimpleAppMain [org.quartz.core.SchedulerSignalerImpl]
Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl

[INFO] 08 七月 01:22:02.873 下午 WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Quartz Scheduler v.2.1.7 created.

[INFO] 08 七月 01:22:02.874 下午 WrapperSimpleAppMain [org.quartz.simpl.RAMJobStore]
RAMJobStore initialized.

[INFO] 08 七月 01:22:02.875 下午 WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Scheduler meta-data: Quartz Scheduler (v2.1.7) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.


[INFO] 08 七月 01:22:02.875 下午 WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'

[INFO] 08 七月 01:22:02.876 下午 WrapperSimpleAppMain [org.quartz.impl.StdSchedulerFactory]
Quartz scheduler version: 2.1.7

[INFO] 08 七月 01:22:02.919 下午 WrapperSimpleAppMain [org.quartz.core.QuartzScheduler]
Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.

